<!DOCTYPE html>
<html lang="en" class="no-js">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap Demo -- failed to build</title>

    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
  </head>

  <body class="bg-red-50 antialiased max-w-4xl mx-auto p-4 my-2">
    <h1 class="text-red-700 text-5xl text-center">
      Build Failed!
    </h1>
    <div class="mt-2">
      <div class="text-gray-700 text-center font-semibold">11 Mar 2025 20:04:42 UTC</div>
    </div>
    <div class="mt-4">
      <div class="text-red-700 bg-red-100 border border-red-200 p-4 rounded text-center font-semibold">
        Unless all site previews are broken, this is a problem with the
        <a class="underline"
          href="https://pypi.org/project/sphinx-bootstrap-theme/"><code>sphinx-bootstrap-theme</code></a>
        package.
      </div>
    </div>
    <div class="mt-4">
      <div class="text-gray-700 text-center font-semibold">Configuration</div>
      <pre class="bg-gray-50 border my-2 shadow rounded p-2 overflow-auto">{&#39;html_theme&#39;: &#39;bootstrap&#39;, &#39;html_theme_path&#39;: &#39;sphinx_bootstrap_theme.get_html_theme_path()&#39;}</pre>
    </div>
    <div class="mt-4">
      <div class="text-gray-700 text-center font-semibold">Output</div>
      <pre class="bg-gray-50 border my-2 shadow rounded p-2 overflow-auto">======================================== stdout ========================================
[01mRunning Sphinx v8.2.3[39;49;00m
[01mloading translations [en]... [39;49;00mlocale_dir /home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/locales/en/LC_MESSAGES does not exist
locale_dir /home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/locales/en/LC_MESSAGES does not exist
done
Original exception:
Traceback (most recent call last):
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/registry.py&#34;, line 541, in load_extension
  File &#34;/usr/lib/python3.12/importlib/__init__.py&#34;, line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1387, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1360, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1331, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 935, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 995, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 488, in _call_with_frames_removed
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/linkcheck.py&#34;, line 32, in &lt;module&gt;
    uri_re = re.compile(&#39;([a-z]+:)?//&#39;)  # matches to foo:// and // (a protocol relative URL)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named &#39;sphinx.util.http_date&#39;


======================================== stderr ========================================

[91mExtension error![39;49;00m

Versions
========

* Platform:         linux; (Linux-6.8.0-1021-azure-x86_64-with-glibc2.39)
* Python version:   3.12.3 (CPython)
* Sphinx version:   8.2.3
* Docutils version: 0.21.2
* Jinja2 version:   3.1.6
* Pygments version: 2.19.1

Last Messages
=============

None.

Loaded Extensions
=================

None.

Traceback
=========

    Traceback (most recent call last):
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/registry.py&#34;, line 541, in load_extension
      File &#34;/usr/lib/python3.12/importlib/__init__.py&#34;, line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1387, in _gcd_import
      File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1360, in _find_and_load
      File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1331, in _find_and_load_unlocked
      File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 935, in _load_unlocked
      File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 995, in exec_module
      File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 488, in _call_with_frames_removed
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/linkcheck.py&#34;, line 32, in &lt;module&gt;
        uri_re = re.compile(&#39;([a-z]+:)?//&#39;)  # matches to foo:// and // (a protocol relative URL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ModuleNotFoundError: No module named &#39;sphinx.util.http_date&#39;
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/cmd/build.py&#34;, line 414, in build_main
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/application.py&#34;, line 287, in __init__
        filename = path.join(self.doctreedir, ENV_PICKLE_FILENAME)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/application.py&#34;, line 489, in setup_extension
        document is parsed -- this means that the whole environment must be
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/registry.py&#34;, line 544, in load_extension
    sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: No module named &#39;sphinx.util.http_date&#39;)


The full traceback has been saved in:
/tmp/sphinx-err-lzimeqqi.log

To report this error to the developers, please open an issue at &lt;https://github.com/sphinx-doc/sphinx/issues/&gt;. Thanks!
Please also report this if it was a user error, so that a better error message can be provided next time.
</pre>
    </div>
  </body>

</html>